export type LakeCode = "ls" | "lm" | "lh" | "lmh" | "le" | "lo";
export type LayerType = "waves" | "waves-500m" | "water" | "wind" | "temp";

export interface LayerInfo {
  id: string;
  name: string;
  type: LayerType;
  lake?: LakeCode;
  geojsonFile: string;
  hasDirectional: boolean;
  pngFile?: string;
  boundsFile?: string;
  description: string;
  unit: string;
  colorScale: string[];
}

export const LAKE_NAMES: Record<LakeCode, string> = {
  ls: "Superior",
  lm: "Michigan",
  lh: "Huron",
  lmh: "Michigan-Huron",
  le: "Erie",
  lo: "Ontario",
};

// Color scales for different layer types
export const COLOR_SCALES = {
  waves: ["#0000ff", "#00ffff", "#00ff00", "#ffff00", "#ff0000"],
  water: ["#000080", "#0000ff", "#00ffff", "#ffffff"],
  wind: ["#90ee90", "#ffff00", "#ffa500", "#ff0000", "#8b0000"],
  temp: ["#0000ff", "#00ffff", "#00ff00", "#ffff00", "#ff0000"],
};

export const LAYERS: LayerInfo[] = [
  // Lake Superior
  {
    id: "ls-waves",
    name: "Superior - Wave Heights",
    type: "waves",
    lake: "ls",
    geojsonFile: "ls-waves.geojson",
    hasDirectional: false,
    description: "Wave heights from 2.5 km resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "ls-waves-500m",
    name: "Superior - Wave Heights (500m)",
    type: "waves-500m",
    lake: "ls",
    geojsonFile: "ls-waves-500m.geojson",
    hasDirectional: false,
    description: "Wave heights from 500 meter resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "lsofs-water",
    name: "Superior - Water Currents",
    type: "water",
    lake: "ls",
    geojsonFile: "lsofs-water.geojson",
    hasDirectional: true,
    pngFile: "lsofs-water.png",
    boundsFile: "lsofs-water.json",
    description: "Water current speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.water,
  },
  {
    id: "lsofs-wind",
    name: "Superior - Wind Speed",
    type: "wind",
    lake: "ls",
    geojsonFile: "lsofs-wind.geojson",
    hasDirectional: true,
    pngFile: "lsofs-wind.png",
    boundsFile: "lsofs-wind.json",
    description: "Wind speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.wind,
  },
  {
    id: "lsofs-temp",
    name: "Superior - Surface Temperature",
    type: "temp",
    lake: "ls",
    geojsonFile: "lsofs-temp.geojson",
    hasDirectional: false,
    description: "Surface water temperature",
    unit: "°C",
    colorScale: COLOR_SCALES.temp,
  },

  // Lake Michigan
  {
    id: "lm-waves",
    name: "Michigan - Wave Heights",
    type: "waves",
    lake: "lm",
    geojsonFile: "lm-waves.geojson",
    hasDirectional: false,
    description: "Wave heights from 2.5 km resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "lm-waves-500m",
    name: "Michigan - Wave Heights (500m)",
    type: "waves-500m",
    lake: "lm",
    geojsonFile: "lm-waves-500m.geojson",
    hasDirectional: false,
    description: "Wave heights from 500 meter resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "lmofs-water",
    name: "Michigan - Water Currents",
    type: "water",
    lake: "lm",
    geojsonFile: "lmofs-water.geojson",
    hasDirectional: true,
    pngFile: "lmofs-water.png",
    boundsFile: "lmofs-water.json",
    description: "Water current speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.water,
  },
  {
    id: "lmofs-wind",
    name: "Michigan - Wind Speed",
    type: "wind",
    lake: "lm",
    geojsonFile: "lmofs-wind.geojson",
    hasDirectional: true,
    pngFile: "lmofs-wind.png",
    boundsFile: "lmofs-wind.json",
    description: "Wind speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.wind,
  },
  {
    id: "lmofs-temp",
    name: "Michigan - Surface Temperature",
    type: "temp",
    lake: "lm",
    geojsonFile: "lmofs-temp.geojson",
    hasDirectional: false,
    description: "Surface water temperature",
    unit: "°C",
    colorScale: COLOR_SCALES.temp,
  },

  // Lake Huron
  {
    id: "lh-waves",
    name: "Huron - Wave Heights",
    type: "waves",
    lake: "lh",
    geojsonFile: "lh-waves.geojson",
    hasDirectional: false,
    description: "Wave heights from 2.5 km resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "lh-waves-500m",
    name: "Huron - Wave Heights (500m)",
    type: "waves-500m",
    lake: "lh",
    geojsonFile: "lh-waves-500m.geojson",
    hasDirectional: false,
    description: "Wave heights from 500 meter resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "lhofs-water",
    name: "Huron - Water Currents",
    type: "water",
    lake: "lh",
    geojsonFile: "lhofs-water.geojson",
    hasDirectional: true,
    pngFile: "lhofs-water.png",
    boundsFile: "lhofs-water.json",
    description: "Water current speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.water,
  },
  {
    id: "lhofs-wind",
    name: "Huron - Wind Speed",
    type: "wind",
    lake: "lh",
    geojsonFile: "lhofs-wind.geojson",
    hasDirectional: true,
    pngFile: "lhofs-wind.png",
    boundsFile: "lhofs-wind.json",
    description: "Wind speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.wind,
  },
  {
    id: "lhofs-temp",
    name: "Huron - Surface Temperature",
    type: "temp",
    lake: "lh",
    geojsonFile: "lhofs-temp.geojson",
    hasDirectional: false,
    description: "Surface water temperature",
    unit: "°C",
    colorScale: COLOR_SCALES.temp,
  },

  // Lake Erie
  {
    id: "le-waves",
    name: "Erie - Wave Heights",
    type: "waves",
    lake: "le",
    geojsonFile: "le-waves.geojson",
    hasDirectional: false,
    description: "Wave heights from 2.5 km resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "le-waves-500m",
    name: "Erie - Wave Heights (500m)",
    type: "waves-500m",
    lake: "le",
    geojsonFile: "le-waves-500m.geojson",
    hasDirectional: false,
    description: "Wave heights from 500 meter resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "leofs-water",
    name: "Erie - Water Currents",
    type: "water",
    lake: "le",
    geojsonFile: "leofs-water.geojson",
    hasDirectional: true,
    pngFile: "leofs-water.png",
    boundsFile: "leofs-water.json",
    description: "Water current speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.water,
  },
  {
    id: "leofs-wind",
    name: "Erie - Wind Speed",
    type: "wind",
    lake: "le",
    geojsonFile: "leofs-wind.geojson",
    hasDirectional: true,
    pngFile: "leofs-wind.png",
    boundsFile: "leofs-wind.json",
    description: "Wind speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.wind,
  },
  {
    id: "leofs-temp",
    name: "Erie - Surface Temperature",
    type: "temp",
    lake: "le",
    geojsonFile: "leofs-temp.geojson",
    hasDirectional: false,
    description: "Surface water temperature",
    unit: "°C",
    colorScale: COLOR_SCALES.temp,
  },

  // Lake Ontario
  {
    id: "lo-waves",
    name: "Ontario - Wave Heights",
    type: "waves",
    lake: "lo",
    geojsonFile: "lo-waves.geojson",
    hasDirectional: false,
    description: "Wave heights from 2.5 km resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "lo-waves-500m",
    name: "Ontario - Wave Heights (500m)",
    type: "waves-500m",
    lake: "lo",
    geojsonFile: "lo-waves-500m.geojson",
    hasDirectional: false,
    description: "Wave heights from 500 meter resolution model",
    unit: "meters",
    colorScale: COLOR_SCALES.waves,
  },
  {
    id: "loofs-water",
    name: "Ontario - Water Currents",
    type: "water",
    lake: "lo",
    geojsonFile: "loofs-water.geojson",
    hasDirectional: true,
    pngFile: "loofs-water.png",
    boundsFile: "loofs-water.json",
    description: "Water current speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.water,
  },
  {
    id: "loofs-wind",
    name: "Ontario - Wind Speed",
    type: "wind",
    lake: "lo",
    geojsonFile: "loofs-wind.geojson",
    hasDirectional: true,
    pngFile: "loofs-wind.png",
    boundsFile: "loofs-wind.json",
    description: "Wind speeds",
    unit: "m/s",
    colorScale: COLOR_SCALES.wind,
  },
  {
    id: "loofs-temp",
    name: "Ontario - Surface Temperature",
    type: "temp",
    lake: "lo",
    geojsonFile: "loofs-temp.geojson",
    hasDirectional: false,
    description: "Surface water temperature",
    unit: "°C",
    colorScale: COLOR_SCALES.temp,
  },
];
